name: wallet
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependency_overrides:
  convert: ^3.0.0
  #  cryptography: ^2.0.1
  fixnum: ^1.0.0
  #  flutter_spinkit: 5.0.0
  #  meta: 1.3.0
  #  analyzer: 1.7.1
#  slope_solana_client:
#    path: ../solana_api

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: #
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  crypto: ^3.0.1    #
  shared_preferences: ^2.0.5 # key value
  provider: ^5.0.0  #
  dio: ^4.0.0 #
  dio_http_cache: ^0.3.0 # http
  image_cropper: ^1.4.0 #
  image_picker: ^0.7.5 #
  local_auth: 1.1.6 #
  auto_size_text: ^3.0.0-nullsafety.0
  permission_handler: ^7.1.0 #
  flutter_inappwebview: ^5.3.2 #webview
  url_launcher: ^6.0.3 # 、
  connectivity: ^3.0.3 #
  date_format: ^2.0.2 #
  flutter_app_badger: ^1.2.0 #
  package_info: ^2.0.0 # App
  device_info: ^2.0.0 #
  flutter_picker: ^2.0.1 #
  path_provider: ^2.0.1 #
  web_socket_channel: ^2.1.0 #
  flutter_easyloading: ^3.0.0 # loading + toast
  flutter_image_compress: ^1.0.0 #
  flutter_svg: ^0.22.0 # svg
  extended_image: ^4.1.0 #  Image , ，，，()，()，()，，
  vm_service: ^7.0.0 #
  pull_to_refresh: ^2.0.0 #
  intl: ^0.17.0 #： 、、、.
  fl_chart: ^0.36.1 #
  qr_flutter: ^4.0.0 #
  sqflite: ^2.0.0+3 #
  encrypt: ^5.0.0 # AES
  scan: 1.4.3 #
  webview_flutter: 2.0.13
  webviewx: ^0.1.0 # webwebview.
  package_info_plus: ^1.0.3 # webpackageInfo
  rxdart: ^0.27.1
  tuple: ^2.0.0
  json_serializable: ^4.1.3
  #
  screen_shot_listen_plugin:
    git:
      url: git url
      ref: master

  #
  image_gallery_saver:
    git:
      url: https://github.com/fzyzcjy/image_gallery_saver.git
      ref: master

  wd_common_package:
    #    path: plugins/wd_common_package
    git:
      url: git url
      ref: master
  slope_solana_client:
    git:
      url: git url
      ref: master
  #    path: ../solana_api

  #  sharesdk_plugin: ^1.3.0 #
  sharesdk_plugin:
    git:
      url: # todo

  video_player: ^2.1.10
  #  audioplayers: ^0.19.1
  system_proxy: 0.0.2
  flutter_staggered_grid_view: 0.4.0

  mock_http_client:
    git:
      url: git url  # todo
      ref: master
  animations: ^2.0.1
  extended_nested_scroll_view: 4.0.0
  decimal: ^1.3.0

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  assets_generator:
    git:
      url: git url  # todo
      ref: master

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    # Android、iOS
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
  assets:

    # assets start

    # GENERATED CODE - DO NOT MODIFY MANUALLY
    # **************************************************************************
    # Auto generated by https://github.com/fluttercandies/assets_generator
    # **************************************************************************

    - assets/
    - assets/fonts/Roboto/
    - assets/image/
    - assets/image/2.0x/
    - assets/image/3.0x/
    - assets/json/
    - assets/svg/

  # assets end
flutter_intl:
  enabled: false